# Job Processor Engine Configuration
# Author: Tushar Kapila

server:
  port: 8087

spring:
  datasource:
    url: jdbc:h2:file:./data/jobprocdb;AUTO_SERVER=TRUE
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: false
  h2:
    console:
      enabled: true
      path: /h2
  batch:
    job:
      enabled: false
  thymeleaf:
    check-template-location: false

jobproc:
  dbReset: false
  defaultNumberOfThreads: 5
  processorJarDirectory: ./processors
  inputFileDirectory: ./inputFiles
  outputFileDirectory: ./outputFiles